repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy
        language_version: python3
        args:
          - --no-warn-unused-ignores
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.7
